# Generated by Django 3.2.12 on 2023-02-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalukRidersModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, null=True)),
                ('firstname', models.CharField(max_length=32)),
                ('secondname', models.CharField(max_length=32, null=True)),
                ('lastname', models.CharField(max_length=32)),
                ('payment', models.BooleanField(default=False)),
                ('region', models.CharField(max_length=1)),
                ('brand', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('kind', models.CharField(max_length=32)),
                ('shirt', models.CharField(max_length=16)),
                ('road', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=3)),
                ('passenger', models.BooleanField(default=False)),
                ('p_shirt', models.CharField(default='', max_length=16, null=True)),
            ],
        ),
    ]
