# Generated by Django 3.2.12 on 2023-02-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_palukridersmodel2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palukridersmodel',
            name='secondname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='palukridersmodel2',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
