# Generated by Django 3.2 on 2023-02-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230211_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palukridersmodel',
            name='p_shirt',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
