# Generated by Django 3.2 on 2023-02-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_palukridersmodel_p_shirt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalukPermamentUnPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField(null=True)),
                ('firstname', models.CharField(max_length=32)),
                ('secondname', models.CharField(blank=True, max_length=32, null=True)),
                ('lastname', models.CharField(max_length=32)),
                ('payment', models.BooleanField(default=False)),
                ('region', models.CharField(max_length=1)),
                ('brand', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('kind', models.CharField(max_length=32)),
                ('shirt', models.CharField(max_length=16)),
                ('road', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=3)),
                ('passenger', models.BooleanField(default=False)),
                ('p_shirt', models.CharField(blank=True, default='', max_length=16, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PalukRidersModel2',
        ),
    ]
