# Generated by Django 3.2 on 2023-02-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230220_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='palukridersmodel',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
