# Generated by Django 3.2.12 on 2023-02-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_palukridersmodel_canceled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palukpermamentunpaymentmodel',
            old_name='ddate',
            new_name='date',
        ),
        migrations.AddField(
            model_name='palukpermamentunpaymentmodel',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
