# Generated by Django 3.2.12 on 2023-02-21 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_copypalukmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.palukridersmodel')),
            ],
        ),
    ]
