# Generated by Django 3.2.12 on 2023-02-21 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_subgroupnamemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.subgroupnamemodel')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.palukridersmodel')),
            ],
        ),
    ]
