# Generated by Django 3.2.12 on 2023-02-21 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_subgroupmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroupmodel',
            name='rider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.palukridersmodel'),
        ),
    ]
